import { and, asc, desc, eq, gt, like, or } from "drizzle-orm";
import { drizzle } from "drizzle-orm/mysql2";
import { InsertProduct, users, sessions, categories, deliveryRates, orderItems, orders, products, subscriptionCodes, codeOrders, manualPayments, InsertSubscriptionCode } from "../drizzle/schema";
import { ENV } from "./_core/env";
import { deleteStorageReference, resolveStorageReference } from "./storage";

let _db: ReturnType<typeof drizzle> | null = null;
export async function getDb() { if (!_db && process.env.DATABASE_URL) { try { _db = drizzle(process.env.DATABASE_URL); } catch { _db = null; } } return _db; }

export async function getUserByPhone(phone: string) { const db = await getDb(); if (!db) return undefined; const rows = await db.select().from(users).where(eq(users.phone, phone)).limit(1); return rows[0]; }
export async function getUserById(id: number) { const db = await getDb(); if (!db) return undefined; const rows = await db.select().from(users).where(eq(users.id, id)).limit(1); return rows[0]; }
export async function createLocalUser(input: { phone: string; passwordHash: string; securityPinHash: string; name?: string }) { const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حاليًا"); return db.insert(users).values({ openId: `local-${input.phone}`, phone: input.phone, passwordHash: input.passwordHash, securityPinHash: input.securityPinHash, name: input.name, role: "user", loginMethod: "local" }); }
export async function deleteUserAccount(id: number) { const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حاليًا"); await db.delete(sessions).where(eq(sessions.userId, id)); return db.delete(users).where(eq(users.id, id)); }
export async function setUserBlocked(id: number, isBlocked: boolean) { const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حاليًا"); if (isBlocked) await db.delete(sessions).where(eq(sessions.userId, id)); return db.update(users).set({ isBlocked }).where(eq(users.id, id)); }
export async function updateUserSecrets(id: number, input: { passwordHash?: string; pinAttempts?: number; pinLockedUntil?: Date | null; lastSignedIn?: Date }) { const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حاليًا"); return db.update(users).set(input).where(eq(users.id, id)); }
export async function updateUserProfile(id: number, input: { name: string; phone: string }) { const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حاليًا"); return db.update(users).set(input).where(eq(users.id, id)); }
export async function updateUserDelivery(id: number, input: { deliveryGovernorate: string; deliveryCity: string; deliveryAddress: string; deliveryNotes?: string | null }) { const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حاليًا"); return db.update(users).set({ ...input, deliveryNotes: input.deliveryNotes || null }).where(eq(users.id, id)); }
export async function listProducts(filters?: { search?: string; stage?: string; type?: string; subject?: string; teacher?: string; limit?: number; includeHidden?: boolean }) { const db = await getDb(); if (!db) return []; const conditions = []; if (!filters?.includeHidden) conditions.push(eq(products.isVisible, true)); if (filters?.stage && filters.stage !== "الكل") conditions.push(eq(products.stage, filters.stage)); if (filters?.type && filters.type !== "الكل") conditions.push(eq(products.type, filters.type)); if (filters?.subject && filters.subject !== "الكل") conditions.push(eq(products.subject, filters.subject)); if (filters?.teacher && filters.teacher !== "الكل") conditions.push(eq(products.teacher, filters.teacher)); if (filters?.search) { const query = `%${filters.search}%`; conditions.push(or(like(products.title, query), like(products.teacher, query), like(products.subject, query))); } return db.select().from(products).where(conditions.length ? and(...conditions) : undefined).orderBy(desc(products.isFeatured), desc(products.createdAt)).limit(filters?.limit ?? 50); }
export async function getProductById(id: number) { const db = await getDb(); if (!db) return undefined; const result = await db.select().from(products).where(eq(products.id, id)).limit(1); return result[0]; }
export async function getCategories() { const db = await getDb(); if (!db) return []; return db.select().from(categories).orderBy(asc(categories.id)); }
export async function listDeliveryRates() { const db = await getDb(); if (!db) return []; return db.select().from(deliveryRates).orderBy(asc(deliveryRates.id)); }
export async function getDeliveryRateConfig(governorate: string) { const db = await getDb(); if (!db) return { shippingCost: 85, extraPerItemCost: 5 }; const row = (await db.select().from(deliveryRates).where(eq(deliveryRates.governorate, governorate)).limit(1))[0]; return { shippingCost: row?.shippingCost ?? 85, extraPerItemCost: row?.extraPerItemCost ?? 5 }; }
export async function getDeliveryRate(governorate: string) { return (await getDeliveryRateConfig(governorate)).shippingCost; }
export async function upsertDeliveryRate(governorate: string, shippingCost: number, extraPerItemCost: number) { const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حاليًا"); const updated = await db.update(deliveryRates).set({ shippingCost, extraPerItemCost }).where(eq(deliveryRates.governorate, governorate)); if (Number(updated[0]?.affectedRows ?? 0) > 0) return updated; return db.insert(deliveryRates).values({ governorate, shippingCost, extraPerItemCost }); }
export function calculateShippingCost(totalQuantity: number, baseRate = 85, extraPerItemCost = 5) { return totalQuantity > 0 ? baseRate + (totalQuantity - 1) * extraPerItemCost : 0; }
async function newOrderNumber(db: Awaited<ReturnType<typeof getDb>>) { if (!db) throw new Error("قاعدة البيانات غير متاحة حاليًا"); for (let attempt = 0; attempt < 30; attempt++) { const value = String(Math.floor(100000 + Math.random() * 900000)); const [bookMatch, codeMatch] = await Promise.all([db.select({ orderNumber: orders.orderNumber }).from(orders).where(eq(orders.orderNumber, value)).limit(1), db.select({ orderNumber: codeOrders.orderNumber }).from(codeOrders).where(eq(codeOrders.orderNumber, value)).limit(1)]); if (!bookMatch.length && !codeMatch.length) return value; } throw new Error("تعذر إنشاء رقم طلب فريد، حاول مرة أخرى"); }
async function newPaymentNumber(db: Awaited<ReturnType<typeof getDb>>) { if (!db) throw new Error("قاعدة البيانات غير متاحة حاليًا"); for (let attempt = 0; attempt < 30; attempt++) { const value = String(Math.floor(100000 + Math.random() * 900000)); const [bookMatch, codeMatch, manualMatch] = await Promise.all([db.select({ paymentNumber: orders.paymentNumber }).from(orders).where(eq(orders.paymentNumber, value)).limit(1), db.select({ paymentNumber: codeOrders.paymentNumber }).from(codeOrders).where(eq(codeOrders.paymentNumber, value)).limit(1), db.select({ paymentNumber: manualPayments.paymentNumber }).from(manualPayments).where(eq(manualPayments.paymentNumber, value)).limit(1)]); if (!bookMatch.length && !codeMatch.length && !manualMatch.length) return value; } throw new Error("تعذر إنشاء رقم دفع فريد، حاول مرة أخرى"); }
export const SPECIALTY_PRODUCT_TYPE = "مذكرات ومراجعات";
export const SPECIALTY_OPTIONS = ["البرمجة", "الكيمياء", "الرياضيات", "الفيزياء", "إدارة الأعمال", "المحاسبة", "علم النفس", "اللغة الفرنسية"] as const;
export function validateOrderItemSpecialty(productType: string, specialty?: string | null) {
  if (productType !== SPECIALTY_PRODUCT_TYPE) return null;
  const value = specialty?.trim() || "";
  if (!SPECIALTY_OPTIONS.includes(value as (typeof SPECIALTY_OPTIONS)[number])) throw new Error("من فضلك اختر المادة التخصصية أولًا");
  return value;
}
export async function createOrder(input: { userId?: number; customerName: string; phone: string; governorate: string; city: string; address: string; notes?: string; paymentMethod?: string; items: Array<{ productId: number; quantity: number; unitPrice?: number; specialty?: string }> }) { const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حاليًا"); const ids = input.items.map(item => item.productId); const catalog = ids.length ? await db.select().from(products).where(or(...ids.map(id => eq(products.id, id)))) : []; if (catalog.length !== ids.length) throw new Error("أحد المنتجات لم يعد متاحًا"); const lines = input.items.map(item => { const product = catalog.find(row => row.id === item.productId); if (!product || !product.isVisible || (!product.isAvailable && !product.isPreorder)) throw new Error(`المنتج غير متاح: ${product?.title || "غير معروف"}`); const specialty = validateOrderItemSpecialty(product.type, item.specialty);
    return { orderId: 0, productId: product.id, quantity: item.quantity, unitPrice: product.price, specialty }; }); const subtotal = lines.reduce((sum, item) => sum + item.unitPrice * item.quantity, 0); const totalQuantity = lines.reduce((sum, item) => sum + item.quantity, 0); const deliveryRate = await getDeliveryRateConfig(input.governorate); const shippingCost = calculateShippingCost(totalQuantity, deliveryRate.shippingCost, deliveryRate.extraPerItemCost); const totalPrice = subtotal + shippingCost; const orderNumber = await newOrderNumber(db); const paymentNumber = await newPaymentNumber(db); const result = await db.insert(orders).values({ orderNumber, paymentNumber, userId: input.userId, customerName: input.customerName, phone: input.phone, governorate: input.governorate, city: input.city, address: input.address, notes: input.notes, subtotal, shippingCost, totalAmount: totalPrice, totalPrice, paymentMethod: input.paymentMethod || "paymob", paymentStatus: "pending", status: "pending" }); const orderId = Number(result[0].insertId); if (lines.length) await db.insert(orderItems).values(lines.map(({ orderId: _ignored, ...item }) => ({ orderId, ...item }))); return { orderId, orderNumber, paymentNumber, subtotal, shippingCost, totalAmount: totalPrice }; }
export async function getOrderById(id: number) { const db = await getDb(); if (!db) return undefined; const rows = await db.select().from(orders).where(eq(orders.id, id)).limit(1); return rows[0]; }
export async function updateOrderPaymob(id: number, input: { paymobOrderId?: string; paymobTransactionId?: string; paymentStatus?: "pending" | "paid" | "failed" | "cancelled"; status?: "pending" | "confirmed" | "processing" | "shipped" | "delivered" | "cancelled" }) { const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حاليًا"); return db.update(orders).set(input).where(eq(orders.id, id)); }
export async function createProduct(input: InsertProduct) { const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حاليًا"); return db.insert(products).values(input); }
export async function updateProduct(id: number, input: Partial<InsertProduct>) { const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حاليًا"); return db.update(products).set(input).where(eq(products.id, id)); }
export async function deleteProduct(id: number) { const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حاليًا"); return db.delete(products).where(eq(products.id, id)); }
async function listOrdersDetailed(userId?: number) {
  const db = await getDb();
  if (!db) return [];
  const rows = await db.select({ order: orders, item: orderItems, product: products }).from(orders).leftJoin(orderItems, eq(orderItems.orderId, orders.id)).leftJoin(products, eq(products.id, orderItems.productId)).where(userId ? eq(orders.userId, userId) : undefined).orderBy(desc(orders.createdAt)).limit(120);
  const grouped = new Map<number, any>();
  for (const row of rows) {
    const current = grouped.get(row.order.id) ?? { ...row.order, items: [] };
    if (row.item) current.items.push({ ...row.item, product: row.product });
    grouped.set(row.order.id, current);
  }
  return Array.from(grouped.values());
}
export async function listOrders() { return listOrdersDetailed(); }
export async function listOrdersForUser(userId: number) { return listOrdersDetailed(userId); }
async function listManualPaymentsDetailed(userId?: number, paymentNumber?: string) { const db = await getDb(); if (!db) return []; const rows = await db.select({ payment: manualPayments, order: orders, codeOrder: codeOrders, item: orderItems, product: products }).from(manualPayments).leftJoin(orders, eq(orders.id, manualPayments.orderId)).leftJoin(codeOrders, eq(codeOrders.id, manualPayments.codeOrderId)).leftJoin(orderItems, eq(orderItems.orderId, orders.id)).leftJoin(products, eq(products.id, orderItems.productId)).where(and(userId ? eq(manualPayments.userId, userId) : undefined, paymentNumber ? like(manualPayments.paymentNumber, `%${paymentNumber}%`) : undefined)).orderBy(desc(manualPayments.createdAt)).limit(300); const grouped = new Map<number, any>(); for (const row of rows) { const current = grouped.get(row.payment.id) ?? { ...row.payment, order: row.order || row.codeOrder, items: [] }; if (row.item) current.items.push({ ...row.item, product: row.product }); grouped.set(row.payment.id, current); } return Array.from(grouped.values()); }
async function resolveManualPaymentProofs(payments: any[]) { return Promise.all(payments.map(async payment => { if (!payment.transferScreenshot?.startsWith("payment-proofs/") && !payment.transferScreenshot?.startsWith("supabase://")) return payment; try { return { ...payment, transferScreenshot: await resolveStorageReference(payment.transferScreenshot) }; } catch (error) { console.error(`[Storage] Failed to create payment-proof signed URL for payment ${payment.id}:`, error); return { ...payment, transferScreenshot: "" }; } })); }
export async function listManualPayments(userId?: number, paymentNumber?: string) { return resolveManualPaymentProofs(await listManualPaymentsDetailed(userId, paymentNumber)); }
export async function deleteManualPayment(id: number, adminId: number) { const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حاليًا"); const payment = (await db.select().from(manualPayments).where(eq(manualPayments.id, id)).limit(1))[0]; if (!payment) throw new Error("عملية الدفع غير موجودة"); if (payment.transferScreenshot?.startsWith("payment-proofs/") || payment.transferScreenshot?.startsWith("supabase://")) await deleteStorageReference(payment.transferScreenshot); await db.delete(manualPayments).where(eq(manualPayments.id, id)); return { success: true, deletedBy: adminId }; }
export async function purgeReviewedPaymentProof(payment: typeof manualPayments.$inferSelect, db: NonNullable<Awaited<ReturnType<typeof getDb>>>, removeReference = deleteStorageReference) {
  const reference = payment.transferScreenshot;
  const isSupabaseProof = reference.startsWith("payment-proofs/") || reference.startsWith("supabase://payment-proofs/");
  if (!isSupabaseProof) return false;
  await removeReference(reference);
  await db.update(manualPayments).set({ transferScreenshot: "" }).where(eq(manualPayments.id, payment.id));
  return true;
}
export async function createManualPayment(input: { orderId?: number; codeOrderId?: number; userId: number; paymentMethod: "vodafone_cash" | "orange_cash" | "we_pay" | "etisalat_cash"; walletPhone: string; transferScreenshot: string }) {
  const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حاليًا");
  const order = input.orderId ? (await db.select().from(orders).where(and(eq(orders.id, input.orderId), eq(orders.userId, input.userId))).limit(1))[0] : undefined;
  const codeOrder = input.codeOrderId ? (await db.select().from(codeOrders).where(and(eq(codeOrders.id, input.codeOrderId), eq(codeOrders.userId, input.userId))).limit(1))[0] : undefined;
  if (!order && !codeOrder) throw new Error("الطلب غير موجود أو لا تملك صلاحية الوصول إليه");
  const paymentStatus = codeOrder?.paymentStatus || order?.paymentStatus; if (paymentStatus === "paid") throw new Error("تم تأكيد دفع هذا الطلب بالفعل");
  const existing = await db.select().from(manualPayments).where(and(input.codeOrderId ? eq(manualPayments.codeOrderId, input.codeOrderId) : eq(manualPayments.orderId, input.orderId || 0), or(eq(manualPayments.paymentStatus, "pending_review"), eq(manualPayments.paymentStatus, "approved")))).limit(1);
  if (existing.length) throw new Error("يوجد إثبات دفع قيد المراجعة لهذا الطلب بالفعل");
  const paymentNumber = await newPaymentNumber(db); const customerName = order?.customerName || codeOrder?.customerName || "مستخدم Areehlak"; const customerPhone = order?.phone || codeOrder?.phone || ""; const amount = order?.totalAmount || order?.totalPrice || codeOrder?.totalAmount || 0;
  const result = await db.insert(manualPayments).values({ paymentNumber, orderId: order?.id || 0, codeOrderId: codeOrder?.id || null, userId: input.userId, customerName, customerPhone, paymentMethod: input.paymentMethod, walletPhone: input.walletPhone, amount, transferScreenshot: input.transferScreenshot, paymentStatus: "pending_review" });
  if (order) await db.update(orders).set({ paymentMethod: input.paymentMethod, paymentStatus: "pending", status: "pending" }).where(eq(orders.id, order.id));
  else if (codeOrder) await db.update(codeOrders).set({ paymentStatus: "pending" }).where(eq(codeOrders.id, codeOrder.id));
  return { paymentId: Number(result[0].insertId), paymentNumber, orderId: order?.id || codeOrder?.id };
}

async function sendWhatsAppText(phone: string, body: string) { if (!ENV.whatsappAccessToken || !ENV.whatsappPhoneNumberId) { console.warn("[WhatsApp] Credentials are not configured; confirmation was not sent"); return; } const recipient = phone.replace(/\D/g, "").replace(/^0/, "20"); try { const response = await fetch(`https://graph.facebook.com/v22.0/${ENV.whatsappPhoneNumberId}/messages`, { method: "POST", headers: { Authorization: `Bearer ${ENV.whatsappAccessToken}`, "Content-Type": "application/json" }, body: JSON.stringify({ messaging_product: "whatsapp", to: recipient, type: "text", text: { preview_url: false, body } }) }); if (!response.ok) console.error("[WhatsApp] Send failed:", await response.text()); } catch (error) { console.error("[WhatsApp] Send error:", error); } }
async function sendBookOrderConfirmation(orderId: number) { const db = await getDb(); if (!db) return; const rows = await db.select({ order: orders, item: orderItems, product: products }).from(orders).leftJoin(orderItems, eq(orderItems.orderId, orders.id)).leftJoin(products, eq(products.id, orderItems.productId)).where(eq(orders.id, orderId)); const first = rows[0]; if (!first) return; const itemLines = rows.filter(row => row.item).map(row => `- ${row.product?.title || "منتج"} × ${row.item?.quantity || 1} (${row.item?.unitPrice || 0} ج.م)`).join("\n"); const message = `تم تأكيد طلب الدفع ✅\nرقم الطلب: ${first.order.orderNumber}\nالاسم: ${first.order.customerName}\nالهاتف: ${first.order.phone}\nالعنوان: ${first.order.governorate} - ${first.order.city} - ${first.order.address}\nالمنتجات:\n${itemLines}\nسعر المنتجات: ${first.order.subtotal} ج.م\nالتوصيل: ${first.order.shippingCost} ج.م\nالإجمالي: ${first.order.totalAmount || first.order.totalPrice} ج.م`; await sendWhatsAppText(first.order.phone, message); }
export async function approveManualPayment(id: number, adminId: number) { const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حاليًا"); const payment = (await db.select().from(manualPayments).where(eq(manualPayments.id, id)).limit(1))[0]; if (!payment) throw new Error("عملية الدفع غير موجودة"); if (payment.paymentStatus === "approved") { await purgeReviewedPaymentProof(payment, db); return { ...payment, transferScreenshot: "", paymentStatus: "approved" as const }; } await db.update(manualPayments).set({ paymentStatus: "approved", reviewedAt: new Date(), reviewedBy: adminId, rejectionReason: null }).where(eq(manualPayments.id, id)); if (payment.codeOrderId) await updateCodeOrderPayment(payment.codeOrderId, "paid"); else { await db.update(orders).set({ paymentStatus: "paid", status: "confirmed" }).where(eq(orders.id, payment.orderId)); await sendBookOrderConfirmation(payment.orderId); } await purgeReviewedPaymentProof(payment, db); return { ...payment, transferScreenshot: "", paymentStatus: "approved" as const }; }
export async function rejectManualPayment(id: number, adminId: number, rejectionReason: string) { const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حاليًا"); const payment = (await db.select().from(manualPayments).where(eq(manualPayments.id, id)).limit(1))[0]; if (!payment) throw new Error("عملية الدفع غير موجودة"); await db.update(manualPayments).set({ paymentStatus: "rejected", reviewedAt: new Date(), reviewedBy: adminId, rejectionReason }).where(eq(manualPayments.id, id)); if (payment.codeOrderId) await updateCodeOrderPayment(payment.codeOrderId, "cancelled"); else await db.update(orders).set({ paymentStatus: "cancelled", status: "cancelled" }).where(eq(orders.id, payment.orderId)); await purgeReviewedPaymentProof(payment, db); return { success: true }; }
export async function reopenManualPayment(id: number, adminId: number) { const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حاليًا"); const payment = (await db.select().from(manualPayments).where(eq(manualPayments.id, id)).limit(1))[0]; if (!payment) throw new Error("عملية الدفع غير موجودة"); await db.update(manualPayments).set({ paymentStatus: "pending_review", reviewedAt: null, reviewedBy: null, rejectionReason: null }).where(eq(manualPayments.id, id)); if (payment.codeOrderId) await updateCodeOrderPayment(payment.codeOrderId, "pending"); else await db.update(orders).set({ paymentStatus: "pending", status: "pending" }).where(eq(orders.id, payment.orderId)); return { success: true }; }
export async function updateOrderStatus(id: number, status: "pending" | "processing" | "shipped" | "delivered" | "cancelled") { const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حاليًا"); return db.update(orders).set({ status }).where(eq(orders.id, id)); }
export async function deleteOrder(id: number) { const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حاليًا"); await db.delete(orderItems).where(eq(orderItems.orderId, id)); return db.delete(orders).where(eq(orders.id, id)); }
export async function listUsers(phone?: string) { const db = await getDb(); if (!db) return []; const normalizedPhone = phone?.replace(/\D/g, ""); const condition = normalizedPhone ? like(users.phone, `%${normalizedPhone}%`) : undefined; return db.select({ id: users.id, name: users.name, email: users.email, phone: users.phone, role: users.role, isBlocked: users.isBlocked, createdAt: users.createdAt }).from(users).where(condition).orderBy(desc(users.createdAt)).limit(100); }

export async function listSubscriptionCodes(_includeSold = false) { const db = await getDb(); if (!db) return []; return db.select().from(subscriptionCodes).orderBy(desc(subscriptionCodes.createdAt)).limit(200); }
export async function createSubscriptionCode(input: InsertSubscriptionCode) { const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حاليًا"); return db.insert(subscriptionCodes).values(input); }
export async function deleteSubscriptionCode(id: number) { const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حاليًا"); return db.delete(subscriptionCodes).where(and(eq(subscriptionCodes.id, id), eq(subscriptionCodes.isSold, false))); }
function newSerial() { return String(Math.floor(100000 + Math.random() * 900000)); }
export async function createCodeOrder(input: { userId: number; codeId: number; customerName: string; phone: string; deliveryMethod: "home_delivery"; governorate?: string; city?: string; address?: string; notes?: string }) {
  const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حاليًا");
  const available = await db.select().from(subscriptionCodes).where(eq(subscriptionCodes.id, input.codeId)).limit(1);
  const code = available[0]; if (!code) throw new Error("الكود غير موجود حاليًا");
  if (input.deliveryMethod === "home_delivery" && (!input.governorate || !input.city || !input.address)) throw new Error("بيانات التوصيل مطلوبة عند اختيار التوصيل للمنزل");
  const orderNumber = await newOrderNumber(db); const paymentNumber = await newPaymentNumber(db);
  let serial = newSerial();
  for (let attempt = 0; attempt < 8; attempt++) { const existing = await db.select({ id: codeOrders.id }).from(codeOrders).where(eq(codeOrders.serial, serial)).limit(1); if (!existing.length) break; serial = newSerial(); }
  const shippingCost = await getDeliveryRate(input.governorate || ""); const serviceFee = 0;
  const result = await db.insert(codeOrders).values({ orderNumber, paymentNumber, userId: input.userId, codeId: code.id, serial, customerName: input.customerName, phone: input.phone, deliveryMethod: input.deliveryMethod, governorate: input.governorate || null, city: input.city || null, address: input.address || null, notes: input.notes || null, amount: code.price, shippingCost, serviceFee, totalAmount: code.price + shippingCost + serviceFee, deliveryStatus: "pending", paymentStatus: "pending" });
  const orderId = Number(result[0].insertId); const totalAmount = code.price + shippingCost + serviceFee; return { orderId, orderNumber, paymentNumber, serial, amount: code.price, shippingCost, serviceFee, totalAmount, teacherName: code.teacherName, planType: code.planType };
}
export async function getCodeOrderById(id: number) { const db = await getDb(); if (!db) return undefined; const rows = await db.select().from(codeOrders).where(eq(codeOrders.id, id)).limit(1); return rows[0]; }
export async function updateCodeOrderPaymob(id: number, input: { paymobOrderId?: string; paymentStatus?: "pending" | "paid" | "failed" | "cancelled"; paymentTransactionId?: string }) { const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حاليًا"); return db.update(codeOrders).set(input).where(eq(codeOrders.id, id)); }
export async function listCodeOrders(userId?: number) { const db = await getDb(); if (!db) return []; return db.select({ order: codeOrders, code: subscriptionCodes, user: users }).from(codeOrders).leftJoin(subscriptionCodes, eq(subscriptionCodes.id, codeOrders.codeId)).leftJoin(users, eq(users.id, codeOrders.userId)).where(userId ? eq(codeOrders.userId, userId) : undefined).orderBy(desc(codeOrders.createdAt)).limit(200); }
async function sendCodeOrderConfirmation(orderId: number) { const db = await getDb(); if (!db) return; const rows = await db.select({ order: codeOrders, code: subscriptionCodes }).from(codeOrders).leftJoin(subscriptionCodes, eq(subscriptionCodes.id, codeOrders.codeId)).where(eq(codeOrders.id, orderId)).limit(1); const row = rows[0]; if (!row) return; const message = `تم تأكيد طلب الدفع ✅\nرقم الطلب: ${row.order.orderNumber}\nطريقة الاستلام: توصيل للمنزل\nالعنوان: ${row.order.governorate} - ${row.order.city} - ${row.order.address}\nالاسم: ${row.order.customerName}\nالهاتف: ${row.order.phone}\nالكود: ${row.code?.teacherName || "كود تعليمي"}\nالباقة: ${row.code?.planType === "three_months" ? "كورس مجمع 3 شهور" : "باقة شهرية"}\nسعر الكود: ${row.order.amount} ج.م\nالتوصيل: ${row.order.shippingCost} ج.م\nالإجمالي: ${row.order.totalAmount} ج.م`; await sendWhatsAppText(row.order.phone, message); }
export async function updateCodeOrderPayment(id: number, paymentStatus: "pending" | "paid" | "failed" | "cancelled", paymentTransactionId?: string) { const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حاليًا"); const existing = (await db.select({ deliveryMethod: codeOrders.deliveryMethod }).from(codeOrders).where(eq(codeOrders.id, id)).limit(1))[0]; const result = await db.update(codeOrders).set({ paymentStatus, paymentTransactionId, paidAt: paymentStatus === "paid" ? new Date() : null, deliveryStatus: paymentStatus === "paid" ? (existing?.deliveryMethod === "home_delivery" ? "processing" : "delivered") : paymentStatus === "cancelled" ? "cancelled" : "pending" }).where(eq(codeOrders.id, id)); if (paymentStatus === "paid") await sendCodeOrderConfirmation(id); if (paymentStatus === "failed" || paymentStatus === "cancelled") { const order = await db.select({ codeId: codeOrders.codeId }).from(codeOrders).where(eq(codeOrders.id, id)).limit(1); if (order[0]) await db.update(subscriptionCodes).set({ isSold: false }).where(eq(subscriptionCodes.id, order[0].codeId)); } return result; }

export async function updateCodeOrderDeliveryStatus(id: number, deliveryStatus: "pending" | "processing" | "shipped" | "delivered" | "cancelled") { const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حاليًا"); return db.update(codeOrders).set({ deliveryStatus }).where(eq(codeOrders.id, id)); }

// Legacy exports remain only for framework compatibility; local authentication is authoritative.
export async function getUserByOpenId(openId: string) { const db = await getDb(); if (!db) return undefined; const rows = await db.select().from(users).where(eq(users.openId, openId)).limit(1); return rows[0]; }
export async function upsertUser(user: any) { const db = await getDb(); if (!db) return; const phone = user.phone ?? `00000000000${String(user.openId ?? "").slice(-1)}`; const existing = await getUserByOpenId(user.openId); if (existing) return; return db.insert(users).values({ openId: user.openId, phone, passwordHash: "disabled", securityPinHash: "disabled", name: user.name, email: user.email, role: "user", loginMethod: "local" }); }
