import { int, mysqlEnum, mysqlTable, text, timestamp, varchar, boolean } from "drizzle-orm/mysql-core";

export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(), openId: varchar("openId", { length: 64 }).notNull().unique(), phone: varchar("phone", { length: 20 }).notNull().unique(), name: text("name"), email: varchar("email", { length: 320 }), passwordHash: text("passwordHash").notNull(), securityPinHash: text("securityPinHash").notNull(), pinAttempts: int("pinAttempts").default(0).notNull(), pinLockedUntil: timestamp("pinLockedUntil"), deliveryGovernorate: varchar("deliveryGovernorate", { length: 100 }), deliveryCity: varchar("deliveryCity", { length: 120 }), deliveryAddress: text("deliveryAddress"), deliveryNotes: text("deliveryNotes"), loginMethod: varchar("loginMethod", { length: 64 }).default("local"), role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(), isBlocked: boolean("isBlocked").default(false).notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(), lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});
export const sessions = mysqlTable("sessions", { id: int("id").autoincrement().primaryKey(), userId: int("userId").notNull(), tokenHash: varchar("tokenHash", { length: 128 }).notNull().unique(), expiresAt: timestamp("expiresAt").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const categories = mysqlTable("categories", { id: int("id").autoincrement().primaryKey(), name: varchar("name", { length: 120 }).notNull(), slug: varchar("slug", { length: 120 }).notNull().unique(), description: text("description"), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const deliveryRates = mysqlTable("deliveryRates", { id: int("id").autoincrement().primaryKey(), governorate: varchar("governorate", { length: 100 }).notNull().unique(), shippingCost: int("shippingCost").notNull().default(85),
  extraPerItemCost: int("extraPerItemCost").default(5).notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() });
export const products = mysqlTable("products", {
  id: int("id").autoincrement().primaryKey(), title: varchar("title", { length: 220 }).notNull(), slug: varchar("slug", { length: 220 }).notNull().unique(), teacher: varchar("teacher", { length: 160 }), publisher: varchar("publisher", { length: 160 }), subject: varchar("subject", { length: 100 }).notNull(), stage: varchar("stage", { length: 100 }).notNull(), grade: varchar("grade", { length: 100 }), type: varchar("type", { length: 100 }).notNull(), category: varchar("category", { length: 120 }).notNull().default("كتب خارجية"), price: int("price").notNull(), originalPrice: int("originalPrice"), imageUrl: text("imageUrl").notNull(), description: text("description").notNull(), pages: int("pages"), stock: int("stock").default(0).notNull(), isVisible: boolean("isVisible").default(true).notNull(), isAvailable: boolean("isAvailable").default(true).notNull(), isPreorder: boolean("isPreorder").default(false).notNull(), isFeatured: boolean("isFeatured").default(false).notNull(), isBestseller: boolean("isBestseller").default(false).notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});
export const orders = mysqlTable("orders", { id: int("id").autoincrement().primaryKey(), orderNumber: varchar("orderNumber", { length: 6 }).notNull().unique(), paymentNumber: varchar("paymentNumber", { length: 6 }).notNull().unique(), userId: int("userId"), customerName: varchar("customerName", { length: 160 }).notNull(), phone: varchar("phone", { length: 30 }).notNull(), governorate: varchar("governorate", { length: 100 }).notNull(), city: varchar("city", { length: 120 }).notNull(), address: text("address").notNull(), notes: text("notes"), subtotal: int("subtotal").notNull().default(0), shippingCost: int("shippingCost").notNull().default(0), totalAmount: int("totalAmount").notNull().default(0), totalPrice: int("totalPrice").notNull(), paymentMethod: varchar("paymentMethod", { length: 40 }).notNull().default("paymob"), paymentStatus: mysqlEnum("paymentStatus", ["pending", "paid", "failed", "cancelled"]).default("pending").notNull(), paymobTransactionId: varchar("paymobTransactionId", { length: 80 }), paymobOrderId: varchar("paymobOrderId", { length: 80 }), status: mysqlEnum("status", ["pending", "confirmed", "processing", "shipped", "delivered", "cancelled"]).default("pending").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() });
export const manualPayments = mysqlTable("manualPayments", {
  id: int("id").autoincrement().primaryKey(),
  paymentNumber: varchar("paymentNumber", { length: 6 }).notNull().unique(),
  orderId: int("orderId").notNull().default(0),
  codeOrderId: int("codeOrderId"),
  userId: int("userId").notNull(),
  customerName: varchar("customerName", { length: 160 }).notNull(),
  customerPhone: varchar("customerPhone", { length: 30 }).notNull(),
  paymentMethod: mysqlEnum("paymentMethod", ["vodafone_cash", "orange_cash", "we_pay", "etisalat_cash"]).notNull(),
  walletPhone: varchar("walletPhone", { length: 30 }).notNull(),
  amount: int("amount").notNull(),
  transferScreenshot: text("transferScreenshot").notNull(),
  paymentStatus: mysqlEnum("paymentStatus", ["pending_review", "approved", "rejected"]).default("pending_review").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  reviewedAt: timestamp("reviewedAt"),
  reviewedBy: int("reviewedBy"),
  rejectionReason: text("rejectionReason"),
});
export const orderItems = mysqlTable("orderItems", { id: int("id").autoincrement().primaryKey(), orderId: int("orderId").notNull(), productId: int("productId").notNull(), quantity: int("quantity").notNull(), unitPrice: int("unitPrice").notNull(), specialty: varchar("specialty", { length: 80 }) });
export const subscriptionCodes = mysqlTable("subscriptionCodes", {
  id: int("id").autoincrement().primaryKey(), teacherName: varchar("teacherName", { length: 160 }).notNull(), planType: mysqlEnum("planType", ["monthly", "three_months"]).notNull(), price: int("price").notNull(), imageUrl: text("imageUrl"), code: varchar("code", { length: 120 }).notNull().unique(), isSold: boolean("isSold").default(false).notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});
export const codeOrders = mysqlTable("codeOrders", {
  id: int("id").autoincrement().primaryKey(), orderNumber: varchar("orderNumber", { length: 6 }).notNull().unique(), paymentNumber: varchar("paymentNumber", { length: 6 }).notNull().unique(), userId: int("userId").notNull(), codeId: int("codeId").notNull(), serial: varchar("serial", { length: 6 }).notNull().unique(), customerName: varchar("customerName", { length: 160 }).notNull(), phone: varchar("phone", { length: 30 }).notNull(), deliveryMethod: mysqlEnum("deliveryMethod", ["whatsapp", "home_delivery"]).default("home_delivery").notNull(), governorate: varchar("governorate", { length: 100 }), city: varchar("city", { length: 120 }), address: text("address"), notes: text("notes"), amount: int("amount").notNull(), shippingCost: int("shippingCost").notNull().default(0), serviceFee: int("serviceFee").notNull().default(0), totalAmount: int("totalAmount").notNull().default(0), paymobOrderId: varchar("paymobOrderId", { length: 80 }), deliveryStatus: mysqlEnum("deliveryStatus", ["pending", "processing", "shipped", "delivered", "cancelled"]).default("pending").notNull(), paymentStatus: mysqlEnum("paymentStatus", ["pending", "paid", "failed", "cancelled"]).default("pending").notNull(), paymentTransactionId: varchar("paymentTransactionId", { length: 120 }), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(), paidAt: timestamp("paidAt"),
});
export type User = typeof users.$inferSelect; export type InsertUser = typeof users.$inferInsert; export type Product = typeof products.$inferSelect; export type InsertProduct = typeof products.$inferInsert; export type Category = typeof categories.$inferSelect; export type DeliveryRate = typeof deliveryRates.$inferSelect; export type Order = typeof orders.$inferSelect; export type OrderItem = typeof orderItems.$inferSelect; export type ManualPayment = typeof manualPayments.$inferSelect; export type Session = typeof sessions.$inferSelect; export type SubscriptionCode = typeof subscriptionCodes.$inferSelect; export type InsertSubscriptionCode = typeof subscriptionCodes.$inferInsert; export type CodeOrder = typeof codeOrders.$inferSelect;
